'use client';

interface HighlightProps {
  children: React.ReactNode;
  issueId: string;
  analysis: any;
  activeComment: string | null;
  setActiveComment: (id: string | null) => void;
  isDismissed: boolean;
  onDismiss: (id: string) => void;
}

export function Highlight({ children, issueId, analysis, activeComment, setActiveComment, isDismissed, onDismiss }: HighlightProps) {
  const isActive = activeComment === issueId;
  
  // SMART CHECK: Does the AI specifically have a flag for THIS section?
  const aiFlagMessage = analysis?.section_flags?.[issueId];

  // If dismissed, no analysis, OR the AI didn't flag this specific section, return plain text!
  if (isDismissed || !analysis || !aiFlagMessage) {
    return <span className="font-semibold text-slate-900">{children}</span>;
  }

  return (
    <span className="relative inline">
      <span 
        onClick={(e) => {
          e.stopPropagation();
          setActiveComment(isActive ? null : issueId);
        }}
        className={`cursor-pointer transition-all duration-200 rounded px-1 py-0.5 font-semibold text-slate-900 underline decoration-dotted decoration-amber-400 decoration-2 underline-offset-4
          ${isActive ? 'bg-amber-300 shadow-sm' : 'bg-amber-100/50 hover:bg-amber-200'} 
        `}
      >
        {children}
      </span>

      {isActive && (
        <div 
          className="absolute left-[calc(100%+24px)] top-0 w-80 bg-white border border-amber-200 shadow-2xl rounded-2xl p-5 z-60 animate-in fade-in zoom-in-95 duration-200 cursor-default"
          onClick={(e) => e.stopPropagation()} 
        >
          <div className="absolute top-4 -left-2 w-4 h-4 bg-white border-l border-b border-amber-200 rotate-45"></div>
          
          <div className="flex items-center gap-2 mb-3 border-b border-slate-100 pb-2">
            <div className="w-6 h-6 bg-amber-500 text-white rounded-lg flex items-center justify-center font-bold text-[10px]">AI</div>
            <span className="font-bold text-xs text-slate-800 uppercase tracking-widest">Risk Assessment</span>
          </div>
          
          {/* Show the SPECIFIC flag message generated by the AI */}
          <p className="text-[13px] text-slate-700 leading-relaxed font-medium mb-4">
            {aiFlagMessage}
          </p>
          
          <div className="flex flex-col gap-2">
            <button 
              onClick={() => onDismiss(issueId)} 
              className="w-full py-2 bg-emerald-600 text-white rounded-lg text-[11px] font-bold uppercase tracking-widest hover:bg-emerald-700 transition-colors shadow-sm"
            >
              Issue Resolved / Ignore
            </button>
            <button 
              onClick={() => setActiveComment(null)} 
              className="w-full py-2 bg-slate-100 text-slate-500 rounded-lg text-[11px] font-bold uppercase tracking-widest hover:bg-slate-200 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </span>
  );
}